### ISSUE TITLE
请问你这个项目是看慕课网课程搭建的吗，如果是的话是看哪个？

### ISSUE THREAD

**Issue by biaodigit** [code-mcx/react-ssr#2]

**Comment by code-mcx** [comment]
这个不是的，参考了官方[react-router服务端渲染](https://reacttraining.com/react-router/web/guides/server-rendering)，[redux服务端渲染](https://www.redux.org.cn/docs/recipes/ServerRendering.html),还有[vue-server-renderer](https://www.npmjs.com/package/vue-server-renderer)
