### ISSUE TITLE
关于renderToString使用的疑问

### ISSUE THREAD

**Issue by nimoat** [code-mcx/react-ssr#5]
请教一下，下面这段代码为什么不直接使用 `ReactDOMServer.renderToString(component)` 呢？
`let root = ReactDOMServer.renderToString(
    React.createElement(
    ChunkExtractorManager,
    { extractor },
    component)
);`

**Comment by code-mcx** [comment]
这段代码写在`server`目录下面，使用的时候没有用`babel`转换，`ReactDOMServer.renderToString(<Component/>)`这样的代码需要通过babel转换后才能运行，babel转换jsx后就是`React.createElement(Component)`
